fjord/feedback/tests/test_views.py, fjord/feedback/views.py
If a URL consists solely of whitespace, we should strip the whitespace
and store an empty string in the db.
r?
=> Handle whitespace URLs

bin/lint_commit_msg.py
When the commit message is empty (for example when the developer wants to abort the commit), the commit message lint script throws an exception.
Now the commit message lint gracefully handles this scenario without throwing any errors or exceptions.
=> Fix commit message lint to gracefully handle empty commit message

fjord/base/static/js/fjord_utils.js, fjord/base/static/tests/test_fjord_utils.js, fjord/feedback/static/js/generic_feedback.js
While performing client-side validation of a URL, allow about: and
chrome:// URLs. Similar fix on the server side has already been done
as a part of fixing bug 1057617.
=> [bug 1091716] Allow about: and chrome:// URLs in client-side validation

fjord/feedback/static/js/generic_feedback.js, fjord/feedback/static/js/generic_feedback_dev.js, smoketests/tests/generic/test_validation.py
In bug #1091716, we updated
fjord/feedback/static/js/generic_feedback.js. However, because we're in
the middle of the remote-troubleshooting changes, we have a parallel
generic_feedback_dev.js file which has the remote-troubleshooting
changes and is currently "live".
This commit updates the generic_feedback_dev.js file with the changes we
made to generic_feedback.js.
r?
=> [bug 1091716] Carry changes over to generic_feedback_dev.js

fjord/feedback/api_views.py
We were passing in a tuple to values_dict() which would pass it to ES in
the fields key like this:
'fields': [('id', 'description', ...)],
the problem being that we need to pass it as a list of fields not a list
of a tuple of fields. This fixes that.
r?
=> [bug 1119015] Fix API with ES 1.2.4

fjord/feedback/views.py
This fixes the decorator so that things that trace through it get the
right function name.
r?
This will make New Relic tracing more helpful.
=> Fix the _persist_feedbackdev decorator

bin/vagrant_provision.sh, requirements/dev.txt
This switches the dev.txt requirements file over to peep. Originally I
thought it was easier to keep dev.txt out of peep, but I keep trying
to peep install these, so I'm changing my mind.
Quick r?
=> Switch requirements/dev.txt to peep

fjord/feedback/static/js/generic_feedback_dev.js, fjord/feedback/templates/feedback/generic_feedback.html
This nixes the happy/sad text and replaces it with something better.
It also changes the checkbox to default to checked. In doing that, I had to do some wonky stuff to make sure the data was in the right place. We should redo that later when we can make bigger changes.
Also, I changed the text for the submit button. It's only for en-US since we don't have translations for that string.
r?
=> [bug 1119972] Fix remote-troubleshooting checkbox

docs/getting_started.rst
This helps avoid odd timestamps in the commit history when the host computer is on a different timezone. Please feel free to suggest rewording of the text if appropriate.
=> Document how to configure the timezone of the VM to match the host

fjord/analytics/templates/analytics/analyzer/hb_surveys.html, fjord/heartbeat/admin.py, fjord/heartbeat/models.py, fjord/heartbeat/south_migrations/0009_auto__add_field_survey_description.py
Add a description field to the model making it optional with a default
value of "". Update SurveyAdmin to list the description field. Update
the template used by survey view in the analyzer section to display the
description field
=>  [heartbeat] add description for survey model and view

fjord/settings/__init__.py, requirements/requirements.txt
This is the laziest possible upgrade path. I upgraded celery and it's dependencies and added two lines of code. I had to switch to the unreleased django-celery master tip so that `./manage.py celeryd` would work. There are also fixes for django 1.7 in there that weren't released.
I know we can't do much this week with this other than possibly test it on stage. I tested it locally (`CELERY_ALWAYS_EAGER = False`) and triggered these tasks: celery_health_task, index_chunk_task, index_item_task and unindex_item_task.
This sort of kicks the can down the road for updating the code to use the new API for celery. We have a couple options:
* Ship this as is and keep grinding through the rest of the django 1.7 blockers to get us onto django 1.7 ASAP. Have a followup bug to come back to updating …
=> [bug 1104863] Upgrade to celery v3.1.17

fjord/base/urlresolvers.py, fjord/feedback/tests/test_views.py
This makes it easier to use reverse in tests that involve non-en-US locales.
Before, we'd have to hard-code the url because reverse would do all this
stuff which would make it difficult to specify non-en-US locales. Now
we can do:
url = reverse('some-thing', locale='es')
The changes were based on what Kitsune has.
r?
=> Tweak reverse to allow you to override the locale

fjord/base/browsers.py
https://msdn.microsoft.com/en-us/library/ie/hh869301%28v=vs.85%29.aspx
That suggests that Windows 10.0 using browsers will have a user agent
with "Windows NT 10.0" in it rather than "Windows NT 6.4". Figure we can
handle both for now.
Quick r?
=> Handle Windows 10 user agents in sniffer

fjord/base/browserid.py, fjord/base/templates/base.html, fjord/base/tests/test_auth.py, fjord/settings/base.py, fjord/urls.py, requirements/requirements.txt
* There are changes to how redirects are done. Instead of a 302, it's a field in the JSON response.
* I had to register the helpers manually because django_browserid is failing to do it. @Osmose says he has seen it before or something similar and is just as puzzled.
* There is a new js file to include.
To test manually, I logged in with an existing user and a new user. WFM.
That's it. r? (CC: @Osmose can you eyeball this to see if it makes sense?)
=> [bug 1054001] upgrade to django-browserid v0.11

requirements/requirements.txt
This seems to just work. I ran the test suite and tested the Firefox OS feedback flow. Any other critical paths that should be manually tested?
r?
=> [bug 934979] Upgrade django rest framework to v2.4.4

fjord/analytics/analyzer_views.py, fjord/analytics/static/css/dashboard.less, fjord/analytics/templates/analytics/analyzer/hb_data.html
* add survey filtering to hb data view with drop down
* tweak the summarytable style to have less left/right padding
r?
=> [bug 1127431] Add survey filtering to hbdata view

fjord/feedback/templates/feedback/generic_feedback.html, fjord/feedback/tests/test_views.py
This removes the en-US requirement and the tests that made sure that
requirement was working.
r?
=> [bug 1111641] Enable browser data capture for all locales

bin/peep-2.1.1.py, bin/travis/install.sh, bin/vagrant_provision.sh, docs/getting_started.rst, peep.sh
* upgrade peep to 2.1.1
* rework how we handle the wheels problem so that instead of applying
tweaks to peep directly which is hard to maintain and error-prone,
we do our tweaks in a shell script and tell everyone to use that
* update the documentation, vagrant provision script and travis stuff
to use the new peep.sh
r?
=> [bug 1124379] Upgrade peep and un-goofify it

fjord/search/tasks.py
Occasionally, we'd get this error:
Task fjord.search.tasks.index_item_task with id
10b7fc0e-6f40-4338-9b4f-f449b0906676 raised exception:
'AttributeError("type object \'ResponseMappingType\' has no attribute
\'split\'",)'
What's going on is if indexing fails, then it builds a new task to retry
indexing. When it did that, it was incorrectly building the args
argument using the mapping type instance rather than the stringified
class path representation. This fixes that.
Plus I fixed one of the comments that wasn't appropriate.
r?
=> [bug 1076879] Fix Response indexing retry

fjord/feedback/models.py, fjord/feedback/south_migrations/0042_auto__add_field_product_browser_data_browser.py, fjord/feedback/templates/feedback/generic_feedback.html, fjord/feedback/tests/__init__.py, fjord/feedback/tests/test_views.py, fjord/feedback/views.py
Previously, we had the template code hardcoded to only collect browser
data if the product the user is leaving feedback for was "Firefox".
This prevents us from collecting browser data for "Firefox Dev Edition".
This changes the code so that the Product specifies whether to collect
browser data at all and which browser we'll collect browser data from.
For example, if the product has browser_data_browser=u'Android' and the
user is using Firefox for Android, then we'll add the browser data
collection bits to the template. Otherwise, we won't.
Also, I moved the "should we show the browser data section" bits from
the template to the view and added some better documentation.
r?
=> [bug 1111265] Fix browser data re: products and browsers

bin/crontab/crontab.tpl, fjord/translations/management/commands/translation_daily.py, fjord/translations/models.py, fjord/translations/tests/test_gengo.py
We want an email warning that the Gengo account balance is low to be
sent out once per day rather than every time the sync stuff runs. This
adds a "daily activities" kind of thing to translation modules so that
we can run:
./manage.py translation_daily
and have that run all the things that should happen only once a day.
Additionally, we add a cron job so that this runs in the morning.
r?
=> [bug 1093341] Fix gengo warning emails

requirements/dev.txt
Add the missing dependencies along with their hashes in requirements/dev.txt so that peep will install it.
=> [bug 1130009] Add pyflake and mccabe to requirements/dev.txt with hashes

fjord/analytics/static/js/dashboard.js, fjord/analytics/views.py
Set the count of selected filters to 0 before the actual count is calculated so that if the calculated count is zero, the filter is not excluded. Also fix the JavaScript code to handle 0 in the denominator when calculating the percentage.
Test for this fix has not been written since I have not used PyQuery before and have to figure out how test this.
=> [bug 1053384] Make the filters visible even when there are no results

fjord/analytics/analyzer_views.py, fjord/analytics/forms.py, fjord/analytics/templates/analytics/analyzer/addproducts.html, fjord/base/browsers.py, fjord/feedback/admin.py, fjord/feedback/models.py, fjord/feedback/south_migrations/0044_auto__add_field_product_browser.py, fjord/feedback/south_migrations/0045_populate_browser.py, fjord/feedback/views.py
Previously, we'd only infer the version if the browser from the user
agent matched the product db_name. That doesn't work for Firefox Dev
Edition or Firefox 64.
This fixes that so that we can explicitly state which "browser" a
product is. Then it'll match up, we can appropriately infer the
product version from the user-agent specified browser version, and we
can go home at night and feel like we did a good job at work.
r?
=> [bug 1129085] Infer version for Firefox Dev

docs/testing.rst, requirements/requirements.txt
This is a new version of django-nose that supports django 1.7.
Also a random commit to fix a nit in the docs about test utils.
r?
=> Update django nose

fjord/analytics/views.py
Complete the previous incomplete fix for this bug which did not
handle the sad/happy filters properly when there were no matching
search results.
=> [bug 1053384] Fix selected sad/happy filters not showing up on 0 results

fjord/analytics/analyzer_views.py, fjord/analytics/static/css/dashboard.less, fjord/analytics/templates/analytics/analyzer/hb_data.html
Add a filter for hiding test rows in hb survey answers table. Distinguish them by background color when not hidden.
=> [bug 1130469] Add a filter for hb test rows and distinguish them by color

fjord/feedback/views.py
The persist_feedbackdev decorator persists the querystring setting for
the feedbackdev flag into a cookie using a name that django-waffle will
key off of. That broke when we updated django-waffle since they moved
the value to a new module.
This fixes that to look at the correct module.
Quick r?
=> [bug 1133734] Fix waffle cookie thing

requirements/requirements.txt
This version is compatible with Django 1.7.
r?
=> [bug 1133895] Upgrade grappelli to 2.6.3

fjord/analytics/analyzer_views.py
This requires the sortby querystring arg to be one of the specified
valid values. Otherwise we make it 'id'.
Quick r?
=> [bug 1137430] Validate sortby values

requirements/requirements.txt
This updates the requirements that already matched released versions
to use pypi pinned versions instead of github URLs.
There are still a dozen or so github URLs that need to be sorted out.
r?
=> [bug 1048462] Update some requirements to pinned versions.

requirements/requirements.txt
* switch some of the github url based requirements to equivalent pypi
based requirements
* split the file into two sections: a github url based section at the
top and a pypi based section at the bottom
r?
=> [bug 1048462] Switch some github url reqs to pypi

fjord/base/tests/test_views.py, fjord/base/views.py, fjord/settings/base.py, fjord/wsgi.py, fjord/wsgi_utils.py, wsgi/playdoh.wsgi
* creates DebuggableWSGIHandler which should send more useful error
emails so I can debug API-related problems, plus in DEBUG=True
mode, it'll return text/plain content rather than text/html content
which is a lot easier to read in a terminal when debugging API-related
problems
* created fjord/wsgi.py which is where the wsgi stuff *should* be--we'll
have to get the servers fixed to use this instead of wsgi/playdoh.wsgi
if this works
* for now, wsgi/playdoh.wsgi and fjord/wsgi.py should be identical--the
former is used in production and the latter is used in development,
but should be used in production
r?
=> [bug 1136840] Fix error handling for better debugging: WIP

fjord/wsgi_utils.py
This adds some additional defensive programming to handle all possible
exceptions for the postbody thing.
r?
=> [bug 1139545] Handle all exceptions

.gitmodules, fjord/settings/log_settings.py, requirements/requirements.txt
* switch the import for dictconfig to the django version
* nix nuggets
* specify versions for tower and django-celery neither of which release
versions
Quick r?
=> [bug 1048462] Remove nuggets

wsgi/playdoh.wsgi
This backs out the new WSGIHandler for stage/prod server environments.
When I landed this, I stopped getting the HB errors that I implemented
this to help track down. That's either a fluke or I messed something up.
Backing this out to eliminate the latter possibility.
Quick r?
=> [bug 1136840] Back out new WSGIHandler

docs/maintain.rst, fjord/base/templates/contribute.json
Remove all references to input-dev.allizom.org
=> [bug 1134475] Cleanup all references to input-dev environment

fjord/heartbeat/api_views.py
Add a log_errors flag (defaults to True) to the HeartbeatV2API.rest_error()
method which disables error logging when set to False. Use it to not log
the error when the update_ts error happens.
=> [bug 1144476] stop logging update_ts errors

fjord/feedback/models.py, fjord/translations/admin.py, fjord/translations/models.py, fjord/translations/tasks.py, fjord/translations/tests/test_tasks.py
The previous backfill page pulled all the instances for a given model
and date range (ouch) and then for each instance, told it to go create
translation tasks (double-ouch). That's a ton of work and far exceeds
the amount of time alotted for connections.
This version reimplements that and pushed the work to celery tasks.
r?
=> [bug 1038512] Rewrite translation backfill admin page

fjord/journal/models.py, fjord/translations/management/commands/trans.py, fjord/translations/models.py
This gives me a command-line way to test translation systems. It's a lot
easier than creating feedback and then triggering a translation for it
and then removing the translation from the db.
This just adds a command and tweaks some code to work better. It doesn't affect tests or production or anything else.
r?
=> [bug 1144870] Add trans command

fjord/settings/base.py, fjord/settings/local.py-dist, fjord/settings/test.py, requirements/requirements.txt
* remove some more settings that aren't used anywhere (DOMAIN, PROTOCOL,
PORT)
* move NOSE_ARGS settings from local.py-dist to test.py where they
really should be
* (cosmetic) fix a typo in requirements.txt
* remove DEBUG = True from test.py since Django turns it False for
tests anyhow
Quick r?
=> [bug 1137022] Minor settings cleanup

fjord/feedback/tests/test_api.py
The BooleanField required=True problem is gone now. I uncommented out
the test, but then bumped into a goofy edge case where BooleanField
defaults to False if you do an HTML form post.
So I went through all the test cases and converted them all to JSON
payloads. That fixes this test and is more correct test-wise since our
API docs ask people to use JSON payloads.
Quick r?
=> [bug 1127428] Uncomment booleanfield test

fjord/feedback/static/js/generic_feedback.js
When onpopstate kicks off, we were changing the page, but also tweaking
the history. We don't need to do that last bit since the event only
fires on history changing.
Quick r?
=> [bug 1141056] Fix history in onpopstate

fjord/feedback/sampledata.py, fjord/feedback/tests/__init__.py
This redoes how we generate sample data for feedback responses:
1. adds api responses based on the product
2. changes it to 100 happy + 100 sad + 1000 other responses
3. fixes it so we're looking at product tuples which group a product,
version, platform and useragent together -- previously we did
them separately which resulted in weirdo/impossible combinations
4. adjust the locale generator so it looks a bit more like typical
Input data
This might also fix problems with the smoketests.
r?
=> [bug 910789] Redo sampledata and add api responses

fjord/feedback/static/css/generic_feedback.less
On retina displays, the footer didn't extend all the way to the right
side of the "page". This fixes that.
Quick r?
=> [bug 1155905] Fix footer width in thanks page

requirements/dev.txt
This should stop manage.py from complaining about missing argparse==1.3.0, every time it is run
=> Remove argparse from dev requirements as python > 2.7 has it built-in

fjord/translations/gengo_utils.py, fjord/translations/tests/test_gengo.py
The guess_language() method calls request.post() which sometimes gets
back a response from the Gengo API that's not JSON. This handles that
case and throws a different kind of error that has the content of what
actually got returned in it.
r?
=> [bug 1158473] Fix JSONDecodeError problems

fjord/feedback/models.py, fjord/feedback/tests/test_api.py
Bug #1155600 creates the problem where Firefox OS > 1.3 relies on the
old (busted) behavior where the "happy" field wasn't required and
defaulted to False. This changes the BooleanField back to that behavior
so that Input stops rejecting Firefox OS > 1.3 feedback.
One caveat of this is that all feedback will be "sad" regardless of
whether the user was actually happy or not. That makes me sad, too.
r?
=> [bug 1159882] Change "happy" in API to default to False

fjord/__init__.py, fjord/manage_utils.py
This is in preparation for celery changes that require code to be in
this file as well and need vendor to be setup.
r?
The tests cover the `manage.py` path. The `wsgi.py` path has to be covered by deploying to -stage?
=> Move vendor/ path setup to fjord/__init__.py.

fjord/base/management/commands/celeryd.py, fjord/celery.py, fjord/manage_utils.py, manage.py
We were getting a sporadic "MySQL has gone away" error in production
which we tracked down to not having DJANGO_SETTINGS_MODULE set when the
celery django fixup code executed which meant we were getting the
default celery loader which didn't clean up db connection before working
on celery tasks. Whew.
This fixes that by moving the os.environ.setdefault() line to the top of
manage.py along with a comment.
This also redoes the celeryd.py code so that it's a copy/paste of
the original source from django-celery so it's easier to maintain going
forward if they change their code.
r?
=> [bug 1144159] Rework celeryd code and fix mysql error

docs/alerts_api.rst, fjord/alerts/api_views.py, fjord/alerts/tests/test_api.py, fjord/base/api_utils.py
This cleans up the alerts api code a bit more:
* use DRF exceptions where appropriate
* move "aflavors" validation to serializer and make the error handling
better so that it spits out all errors at once rather than just the
first one it hit
* fix a typo in HTTP 400 for flavors
* add a NotFound exception--this exists in DRF3, so when we upgrade we
can use theirs
r?
=> [bug 1161746] More alerts api code cleanup

fjord/feedback/models.py, fjord/feedback/tests/test_api.py
What was happening was that if the description was whitespace, it would
get validated (it's not blank, so yippie!), and then get stripped and
saved. That resulted in blank descriptions.
This adds validation to make sure we don't get descriptions that are
whitespace.
r?
=> [bug 1165996] Explicitly validate description in api

fjord/feedback/api_views.py, fjord/feedback/tests/test_api.py, fjord/feedback/urls.py
This is a temporary histogram feedback API. "Temporary" in this
case means we'll deprecate it as soon as we write a better one
using Elasticsearch aggregations. As soon as we do that, we'll
deprecate this one.
There's a bunch of FIXMEs in the code. We can fix them if this proves
less temporary than I'd like.
r?
=> [bug 1077596] Temporary histogram feedback API

fjord/base/google_utils.py, fjord/base/tests/test_google_utils.py
This adds a ga_track_event function that lets us capture data and post
it from the server. This is just like what we do currently with statsd,
but it's intended specifically for events and pushes the data to Google
where we can look at event flows.
r?
=> [bug 1169261] Implement ga_track_event

fjord/feedback/templates/feedback/thanks.html
This changes the "get help" link on the thank you page to point directly
to asking a new question rather than to the front page of SUMO per
Verdi's suggestion.
Quick r?
=> [bug 1129615] Change "get help" link to point to AAQ

docs/conventions.rst, fjord/analytics/helpers.py, fjord/analytics/views.py, fjord/base/helpers.py, fjord/base/models.py, fjord/feedback/config.py, fjord/feedback/helpers.py, fjord/feedback/models.py, fjord/suggest/providers/sumosuggest.py
As mentioned in IRC, I created fjord/base/translation.py to create the lazy versions. I am open to other ideas.
r?
=> [bug 1167192] In python, stop using the gettext from tower.

fjord/feedback/templates/feedback/thanks_l10nized.html
This creates a copy of the thank you page which has strings that are
product agnostic. As soon as the strings are translated, we'll ditch the
old version for this version.
r?
=> [bug 1172019] Make thank you page product-agnostic

fjord/suggest/providers/sumosuggest.py
Still can't figure out why we're posting "https://" to GA. Trying this
out to see if it sheds light on the situation.
Quick r?
=> [bug 1173763] Tweak error logging code

fjord/base/google_utils.py
This shouldn't affect how the expression is evaluated, but it does make
it clearer what the intention is.
Quick r?
=> [bug 1173763] Make grouping clearer

fjord/suggest/providers/sumosuggest.py
For the last day, we logged all redirection urls in an attempt to see
whether Input was sending bad data to GA. After looking over 70+
entries, I see no evidence Input is sending bad data to GA.
Given that, I can only assume that Input is fine and GA is displaying
it incorrectly in the Event Flow report.
Given that, I'm removing the logging code.
Quick r?
=> [bug 1173763] Remove logging from sumosuggest provider

bin/l10n_completion.py, bin/stats-po.sh, bin/test_locales.sh, fjord/settings/base.py
To test this, I....
1- Did an extract+merge and verified django.pot and all the django.po files were created.
2- I looked at the django.po files and they didn't have translations, as expected.
3- I copied locale/es/LC_MESSAGES/messages.po to locale/es/LC_MESSAGES/django.po
4- Compiled locales and ran the server.
5- Verified that /es/ is localized but /fr/, for example, isn't
I think that proves that all the parts are right. What did I miss?
r?
=> [bug 1167192] Changed text domain for L10n from messages to django.

bin/compile-linted-mo.sh
We no longer use Python 2.6, so the default here should be whatever the
system python is which is 2.7 on my machine.
Quick r?
=> Fix to use better python

fjord/base/l10n.py, fjord/base/middleware.py, fjord/settings/base.py
From the django docs, I'm pretty sure this is how you activate a locale. https://docs.djangoproject.com/en/1.8/ref/utils/#django.utils.translation.activate
Tower does a bunch of other stuff that I thought we didn't need. But this doesn't work. What am I missing?
=> [bug 1167192] Replace tower's activate().

fjord/settings/base.py
We were getting a TEST_RUNNER warning which was spurious because we're
not using the Django default test runner. However, the warning kicked
off because there were some default settings in our settings.py file
which caused the checker to think we had upgraded from Django 1.5 and
thus needed the warning.
This removes some of those settings and tweaks the code so the spurious
warning doesn't pop up anymore.
r?
=> [bug 1178440] Fix TEST_RUNNER warning

fjord/base/l10n.py, fjord/base/tests/test_templates.py
r?
I admit my testing was lazy. Should I do something different?
=> [bug 1177451] Return safe (jinja2.Markup) strings from _()

.gitmodules, requirements/requirements.txt
This switches django-waffle to the "django-jinja" branch of my fork
which supports django-jinja2. We need to do this to allow us to switch
from jingo to django-jinja when we upgrade to Django 1.8.
It should be the last commit on this branch:
https://github.com/willkg/django-waffle/commits/django-jinja2
Quick r?
=> [bug 1170160] Update django-waffle to willkg fork

fjord/feedback/api_views.py, fjord/feedback/tests/test_api.py
This adds a test and tweaks some test code to make adding the test easier. The actual fix is to make the `.query()` call correct.
Quick r?
=> [bug 1187699] Fix q arg in secret histogram api

fjord/feedback/views.py
This fixes the feedbackdev persistence code. We upgraded django-waffle recently and they moved some stuff around internally. This code never got updated.
r?
=> [bug 1187505] Fix feedbackdev persistence code

fjord/translations/admin.py, fjord/translations/gengo_utils.py, fjord/translations/migrations/0002_gengojob_tier.py, fjord/translations/models.py, fjord/translations/templates/admin/gengo_translator_view.html, fjord/translations/tests/test_gengo.py
Gengo stopped doing synchronous machine translation so I rewrote the
code to do asynchronous translation. Because machine and human
translation are essentially the same now, I unified the two translation
systems and ditched a bunch of code.
r?
=> [bug 1190356] Redo gengo machine translation

Vagrantfile
Replace the direct link to the Ubuntu box on Ubuntu download site with
the official vagrant box on Atlas. This helps with keeping up with the
box updates since Atlas supports box versioning.
=> Use the official Ubuntu vagrant box from Atlas

fjord/heartbeat/api_views.py, fjord/heartbeat/tests/test_api.py
This is a stop gap fix to handle "unknown" as a value for the country
field for HB posts. What's going on now is that it throws an HTTP 400
error. This fixes it so that "unknown" gets changed to "UNK" which is a
valid value.
Ultimately we should fix this in HB. There's a PR to fix it there. Once
it's fixed there, we can undo this change.
r?
=> [bug 1195747] Handle "unknown" for country field in hb post

fjord/base/browsers.py, fjord/base/tests/user_agent_data.json, fjord/feedback/tests/test_views.py
What's going on is that I had handling for iPhone and iPad, but not iPod touch. I fixed that and also added some tests to verify that inferring works correctly.
r?
=> [bug 1192812] Fix firefox for ios inferring

fjord/feedback/models.py, fjord/feedback/tests/test_views.py
I missed this in the previous fix. Bah.
I'll wait for Travis to greenlight it and then self-r+ it and land it.
=> [bug 1192812] Fix platform inferring for firefox for ios

fjord/base/tests/test_auth.py, fjord/base/tests/test_browsers.py, fjord/base/tests/test_domain.py, fjord/base/tests/test_forms.py, fjord/base/tests/test_google_utils.py, fjord/base/tests/test_helpers.py, fjord/base/tests/test_templates.py, fjord/base/tests/test_urlresolvers.py, fjord/base/tests/test_utils.py, fjord/base/tests/test_views.py
files. It replaces eq_ and ok_ with proper assert statements.
=> bug 1193323 : Remove eq_ and ok_ : base

fjord/analytics/tests/test_analyzer_views.py, fjord/analytics/tests/test_utils.py, fjord/analytics/tests/test_views.py
[bug 1193321] Remove eq_ and ok_: analytics
files. It replaces eq_ and ok_ with proper assert statements.
=> [bug 1193321] Remove eq_ and ok_: analytics

.pre-commit-config.yaml, requirements/dev.txt
Update the hash of the pre-commit-hooks repository to that of v0.4.2 which will fix the exceptions caused when running pre-commit hooks. Update pre-commit to the latest version 0.5.4.
=> Fix pre commit exceptions and update pre commit

fjord/redirector/tests/test_dummy.py
files under redirector directory. It replaces eq_ and ok_ with proper
=> [bug 1193328] Remove eq_ and ok_: redirector

fjord/translations/tests/test_gengo.py
files under translations directory. It replaces eq_ and ok_ with proper
=> [bug 1193332] Remove eq_ and ok_: translations

fjord/suggest/tests/test_dummy.py
files under suggest directory. It replaces eq_ and ok_ with proper
=> [bug 1193331] Remove eq_ and ok_: suggest

fjord/search/tests/test_index.py, fjord/search/tests/test_models.py, fjord/search/tests/test_tasks.py, fjord/search/tests/test_utils.py
files under search directory. It replaces eq_ and ok_ with proper
=> [bug 1193330] Remove eq_ and ok_: search

fjord/analytics/static/css/dashboard.less, fjord/analytics/templates/analytics/analyzer/dashboard.html, fjord/base/forms.py, fjord/base/models.py, fjord/base/tests/test_forms.py, fjord/base/tests/test_models.py, fjord/redirector/__init__.py, fjord/redirector/base.py, fjord/settings/base.py, fjord/suggest/providers/sumo/provider.py, fjord/suggest/providers/trigger/admin.py, fjord/suggest/providers/trigger/analyzer_views.py, fjord/suggest/providers/trigger/forms.py, fjord/suggest/providers/trigger/migrations/0001_initial.py, fjord/suggest/providers/trigger/models.py, fjord/suggest/providers/trigger/provider.py, fjord/suggest/providers/trigger/templates/trigger/triggerrule_form.html, fjord/suggest/providers/trigger/templates/trigger/triggerrule_list.html, fjord/suggest/providers/trigger/tests/__init__.py, fjord/suggest/providers/trigger/tests/test_models.py, fjord/suggest/providers/trigger/tests/test_provider.py, fjord/suggest/providers/trigger/urls.py, fjord/urls.py
Implements the Trigger suggester which allows analyzers to set up
trigger rules for adding suggestions to feedback that match those rules.
r?
=> [bug 1175123] Initial implementation of Trigger suggester

fjord/suggest/providers/trigger/models.py, fjord/suggest/providers/trigger/tests/test_models.py
Keywords wouldn't match if bounded by a non-alphnum character. e.g.
"best" would not match "firefox is the best!" because the "!" was
neither an end-of-string nor a whitespace character.
This changes the bounds to \W and adds a test.
r?
=> [bug 1175123] Fix keyword matching

fjord/suggest/providers/sumo/tests/test_sumosuggest.py
files under suggest/providers directory. It replaces eq_ and ok_ with proper
assert statements. This directory was left out while submitting PR #651 .
=> [bug 1193331] Remove eq_ and ok_: suggest.

fjord/feedback/tests/test_api.py, fjord/feedback/tests/test_models.py, fjord/feedback/tests/test_utils.py, fjord/feedback/tests/test_views.py
files under feedback directory. It replaces eq_ and ok_ with proper
=> [bug 1193325] Remove eq_ and ok_: feedback.

requirements/compiled.txt
This only affects local development environments and doesn't affect server environments.
I have a bug open with webops to figure out the server environments side.
The only two things that seem to use lxml are pyquery (which we use in the tests) and translate-toolkit (which we use extracting strings). I don't see evidence of other things using lxml. It's entirely possible that nothing of substance uses it at all.
Given that, I figured I might as well make a PR for it.
r?
=> [bug 1032951] Upgrade lxml to 3.4.4

requirements/requirements.txt
No code changes required. I don't think our DRF code uses anything that
changed between versions.
=> [bug 1203118] Upgrade djangorestframework 3.1.3 -> 3.2.3

fjord/__init__.py, fjord/alerts/tests/test_api.py, fjord/base/admin.py, fjord/events/urls.py, fjord/events/views.py, fjord/heartbeat/admin.py, fjord/heartbeat/api_views.py, fjord/heartbeat/tests/test_api.py, fjord/journal/admin.py, fjord/journal/utils.py, fjord/redirector/__init__.py, fjord/suggest/__init__.py, fjord/translations/admin.py, fjord/translations/models.py, fjord/translations/tasks.py, fjord/translations/tests/test_tasks.py, fjord/translations/tests/test_utils.py, fjord/translations/utils.py, fjord/translations/views.py
Most of the code base uses absolute imports, but we used relative imports in a few places. The case for using relative imports is that it theoretically makes it easier to pluck the code and stick it somewhere else. Sure, but there's no way we're moving this code somewhere else, so I'd rather the imports were clearer and more explicit.
Given that, I changed all the relative imports to absolute imports.
Minor r?
=> Cosmetic: Change relative imports to absolute imports

py.test, requirements/dev.txt
Update the dependencies listed in the bug 1202647.
Get rid of flake8 and its dependencies since we no longer use it
directly. pre-commit installs flake8 from its dependencies in its
own virtualenv and does not use the one we have been installing till
now.
=> [bug 1202647] Update dev requirements

.gitmodules, fjord/settings/base.py, requirements/requirements.txt, vendor/vendor.pth
Input doesn't use django-cronjobs. This removes it from the requirements
and vendor/.
=> [bug 1146686] Remove django-cronjobs

fjord/base/google_utils.py, fjord/base/tests/test_google_utils.py
We have a handful of google_utils tests that need to test that function.
This fixes them so they're all mocked and none of them send actual data.
We have a bunch of other tests that test code that calls google_utils
functions. This fixes the google_utils functions to not send any data
when running in a test context.
r?
=> [bug 1209787] Fix tests sending GA data

fjord/suggest/providers/trigger/static/js/triggerrule.js
The triggerrule testing thing was sending [''] for fields like locale
which are \n delimited textareas. That now causes an HTTP 400 error.
This fixes that by filtering out empty strings before generating the
request to send to the API.
Note: This commit was buried in the django-1.8 pr. I cherry-picked it and removed it from the Django 1.8 pr.
r?
=> [bug 1146686] Fix triggerrule testing

requirements/requirements.txt
NB: The 0.0.8 on pypi has no related tag in the elasticsearch-dsl
repository, so I picked a commit that looks like it might be 0.0.8, but
I don't know for sure.
=> [bug 1200369] Update elasticsearch-dsl to 0.0.8

Vagrantfile
Name the vagrant VM as 'fjord-dev' instead of letting vagrant
name it as fjord_default_<some long random number>.
=> Properly name the vagrant VM

bin/compile-linted-mo.sh
This will cause msgfmt to check the headers of the .po file before it
compiles it to a .mo file. In most cases, the header values don't matter
a lot. However, this validates the Plural-Forms header which is important.
If Plural-Forms header is invalid, then msgfmt will exit with a status
code of 1 and we don't replace the existing .mo file. If it's fine,
then we copy the targettmp file to the destination and we're good to go.
r?
=> [bug 1216624] Add --check-header to msgfmt run

fjord/journal/models.py, fjord/journal/tests/test_models.py
If the msg is too long, then it throws a db error. This truncates the
msg value.
=> Fix msg length

bin/crontab/crontab.tpl
It looks like the script is running just fine, but it's putting the
file in the source tree rather than the web tree and that's not
correct. We need to put it in the web tree so that it's available
everywhere.
Pretty sure this should fix it.
r?
=> [bug 1218381] Fix run_l10n_completion runs

fjord/feedback/config.py, fjord/feedback/forms.py, fjord/feedback/migrations/0009_auto_20151111_1518.py, fjord/feedback/models.py, fjord/feedback/tests/test_api.py, fjord/feedback/tests/test_views.py
This changes the url field to be 1000 characters. Further, it changes
the API and the feedback form handler to allow urls bigger than 1000
characters, but truncate them. It adds a test for the feedback form
handler and fixes the api test. On top of that, it centralizes the
magic number to the config file so I can more easily change it.
=> [bug 1221252] Fix url field handling for feedback

fjord/feedback/config.py, fjord/feedback/migrations/0010_auto_20151112_0708.py, fjord/feedback/models.py, fjord/feedback/tests/test_api.py, fjord/feedback/tests/test_views.py, fjord/feedback/views.py
This changes the field to hold up to 1000 characters. Further, it
changes the code for both the feedback handling view and the api to
truncate user agents longer than 1000 characters. It adds tests. It
centralizes the length in a config constant.
=> [bug 1224014] Fix user agent length issues

fjord/feedback/tests/test_views.py, fjord/feedback/views.py
Old fennec had an in-product form that used the old Input POST
params. This change adds a "source" to that so we can see how much
feedback we're getting from old fennec which will inform us as to
when we can take this code out.
=> [bug 1223625] Tag old fennec feedback with a source

fjord/analytics/analyzer_views.py, fjord/feedback/api_views.py, fjord/feedback/models.py, fjord/feedback/tests/test_api.py
I also redid the api code in ES because previously if a feedback
wasn't saved with the API, then the value would be None which ES
doesn't index and it's harder to query. This changes it so that the
api values are all strings and the None value is now "None".
=> [bug 1223625] Add source and api params to secret histogram api

fjord/translations/admin.py
Initialized outstanding to be an empty list.
=> [bug 1225937] Fix UnboundLocalError in /admin/gengo-translator-view

fjord/translations/admin.py
Fixed the error for the 'seven_days_of_orders' variable
=> [bug 1225937] Fix UnboundLocalError in gengo maintenance admin page

fjord/heartbeat/api_views.py, fjord/heartbeat/tests/test_api.py
Previously, I think it was possible for Input to stomp on a new data
packet with an old one because the updated_ts check would be using on
stale data because we're in a multidb environment and there's
replication lag and all that.
This pins that view so that it always happens on the master db and thus
always sees the current view of the world.
Further, this adds a bunch of statsd calls so we can measure various
scenarios we don't otherwise have a window into.
=> [bug 1229366] Pin hb data view and improve logging

fjord/base/jinja2/base.html, fjord/base/tests/test_utils.py, fjord/feedback/jinja2/feedback/fxos_feedback.html, fjord/feedback/jinja2/feedback/generic_feedback.html, fjord/feedback/jinja2/feedback/picker.html, fjord/feedback/tests/test_views.py, fjord/feedback/urls.py, fjord/feedback/views.py
This splits the picker view from the feedback_router code. Having said
that, the oldandroid code makes that continue to look a bit goofy.
This drops the requirement that we *only* show the Firefox OS form to
users of Firefox OS. With these code changes, if they got to
/feedback/, they'll now go to the picker. We don't get a lot of
Firefox OS feedback. As of 1.3, they have an in-product form that uses
the API anyhow.
This gets rid of the PRODUCT_OVERRIDES scaffolding which we haven't
used in ages and has very much overstayed its welcome.
The end result is a feedback_router that's a little more
straight-forward.
=> [bug 1235423] Refactor feedback_router

fjord/feedback/jinja2/feedback/thanks.html, fjord/feedback/views.py
I goofed when I added support for product_config where the keys to
product slug were product slugs, but what we're storing in the
feedback_response table is the product db_name. Thus doing a lookup
using the product db_name would always fail. Oops!
This fixes that.
=> [bug 1236581] Fix Thank You view

fjord/translations/migrations/0003_auto_20160105_0657.py, fjord/translations/models.py, fjord/translations/tests/test_gengo.py
This cleans up some code I wrote a while ago such that it now uses a
mailing list rather than mailing the admin when there are gengo
balance alerts.
=> [bug 1129703] Switch gengo balance check to use mailing list

fjord/feedback/static/js/generic_feedback.js, smoketests/tests/generic/test_submit.py
This allows you to create a URL that pre-fills the feedback URL.
/feedback/?url=somewebsite.com
=> [bug 1239017] Add URL pre-filling via URL

fjord/base/middleware.py
Django 1.8 changed trans_real.activate such that if you pass in a ''
language, then it does nothing. Since prefixer.locale is '' when
handling an /admin/ request, the request gets handled with the
previously handled request's activated translations.
This fixes that so that if prefixer.locale is '', then we use the
settings.LANGUAGE_CODE to activate the translations.
r?
=> [bug 1215125] Fix whimsical locale in admin

fjord/feedback/jinja2/feedback/android_feedback.html, fjord/feedback/jinja2/feedback/android_thanks.html, fjord/feedback/static/css/android-feedback.less, fjord/feedback/static/js/android_feedback.js, fjord/feedback/tests/test_views.py, fjord/feedback/views.py, fjord/settings/base.py, smoketests/pages/android_feedback_form.py, smoketests/tests/android/test_android_feedback.py
This PR does 2 things. 
1. Includes front-end integration of styles from about:feedback in FxA. Still missing links and integration with "later" and "never". Check the SVG hotness.
2. Addresses the concerns from #722. Specifically...
* doesn't overload PRODUCT_OVERRIDE
* doesn't customize /thanks
* doesn't save happy feedback
=> [bug 1225676] Port fennec feedback form to web

bin/update/update.py, docs/getting_started.rst, docs/l10n.rst, docs/maintain.rst
I didn't touch `bin/update_site.py` because I assumed it was out-of-date as a deploy script, but I didn't want to just remove it. Maybe I should?
The process here is:
1. Merge this branch.
2. File a webops bug to replace the svn directory on staging with a git repo.
3. Once staging has the right directory, deploy this update.
4. Switch Pontoon's Input project over to the new git repo and test the entire process from submitting a Pontoon translation to deploying it to staging.
5. If things go well, repeat steps 2-4 on production.
@mythmon r?
=> Bug 1235417: Switch to git for storing translations.

requirements/dev.txt, requirements/requirements.txt
PyPI is serving us zip files instead of tar.gz/tar.bz files, causing
peep to fail hash verification. I verified the hashes we had against
PyPI's tarballs, diffed their contents against the zipfiles to
ensure they hadn't changed, and then got the hashes of the zipfiles
and added them here.
See https://bitbucket.org/pypa/pypi/issues/436/peep-hash-failures-due-to-being-served-zip
for more info.
=> Fix requirement hashes.

fjord/base/templatetags/jinja_helpers.py, fjord/base/tests/test_helpers.py
When a URL contains unicode, Django's request.get_full_path() returns
a unicode string with percent-encoded unicode strings. parse_qsl fails
to parse this properly, and returns a unicode string with bytes in it,
instead of codepoints. To fix this, we encode the URL in ASCII before
passing it to parse_qsl.
See http://www.lexev.org/en/2013/parse-url-which-chontains-unicode-query-using-urlp/ for a slightly more detailed description.
My local tests are borked so I'm hoping the automated tests will fare better. 
@mythmon r?
=> Fix bug 1264916: Always pass a str to parse_qsl.
