mozilla/fjord

fjord/feedback/models.py
fjord/feedback/tests/test_models.py

Removed the verbose print statements and instead logged the result of purge_data script in the journal.

Fix bug 1114335 - purge_data script should record what happened in journal

---

fjord/feedback/tests/__init__.py
fjord/feedback/tests/test_models.py

Update purge_data test to cover RemoteTroubleshootingInfo objects

---

.gitmodules
fjord/analytics/analyzer_views.py
fjord/base/models.py
fjord/base/tests/test_views.py
fjord/feedback/admin.py
fjord/feedback/models.py
fjord/feedback/tests/test_models.py
fjord/feedback/tests/test_views.py
fjord/journal/models.py
fjord/search/index.py
fjord/search/models.py
fjord/translations/models.py
fjord/translations/tests/test_gengo.py
requirements/requirements.txt
vendor/vendor.pth

This is it. I grep'd for `uncached` and `no_cache` and `caching.base` and am pretty sure I got everything.
Unit tests pass.
Smoke tests pass.
What could go wrong?
r?

[bug 1093222] Remove django-cache-machine 

---

bin/vagrant_provision.sh
fjord/manage_utils.py
peep
requirements/dev.txt

Upgrades to the last peep with the --no-use-wheels provision still in.
Also, this removes the goofy "pip install pip" line.
r?

[bug 1108156] Upgrade peep

---

fjord/feedback/tests/test_views.py
fjord/feedback/views.py

I added a test as for the new code in fjord/feedback/views.py as well.

[bug 1116523] Add respons ID to session

---

fjord/feedback/static/css/generic_feedback.less
fjord/feedback/templates/feedback/generic_feedback.html

Please review this pull request and let me know if I need to correct something.

Back button hit area increased in generic_feedback.html

---

bin/l10n_completion.py

* changed the percent from an integer to a float
* added an "untranslated_words" stat
r?

l10n_completion tweaks

---

.travis.yml
bin/travis/dispatch.sh
bin/travis/install.sh
bin/travis/setup.sh
bin/travis/test.sh
fjord/settings/travis.py-dist
requirements/dev.txt
vendor/tarballs/README

If I did things right, this just might trigger a Travis build.

[bug 1071044] Initial travis setup.

---

requirements/requirements.txt

[bug 1119305] Upgrade django to 1.6.10

---

fjord/feedback/views.py

* nixes the optout metric since it's wrong and hard to get right without
duplicating code
* further, I added email optin metrics and context metrics
Quick r?

[bug 1120952] Fix remotetroubleshooting metrics

---

fjord/feedback/models.py
fjord/feedback/south_migrations/0039_auto__add_responsepi.py
fjord/feedback/south_migrations/0040_responsetroubleshootinginfo_to_responsepi.py
fjord/feedback/south_migrations/0041_auto__del_responsetroubleshootinginfo.py
fjord/feedback/tests/__init__.py
fjord/feedback/tests/test_models.py
fjord/feedback/tests/test_views.py
fjord/feedback/views.py

Renames the ResponseTroubleshootingInfo table to ResponsePI.
r?

[bug 1124497] table rename -- DO NOT MERGE

---

fjord/heartbeat/tests/test_api.py
fjord/heartbeat/views.py

[bug 1126030] Enable CORS for Heartbeat API.

---

bin/vagrant_provision.sh
docs/l10n.rst

No bug - Fixed l10n documentation and added l10n dependencies to vagrant.

---

docs/getting_started.rst

Explain the common problem scenarios encountered on pulling from
Mozilla's repository and how to resolve them and keep the fjord
development environment up to date.
Please review the content and suggest corrections if any.

[bug 1127312] Document how to keep up with changes to fjord in the dev environment

---

requirements/requirements.txt

This has fixes for django 1.7.
r?

[bug 1118765] Upgrade jingo to master tip.

---

fjord/base/tests/__init__.py
requirements/requirements.txt

This is a dot release that adds the new migrations for django 1.7.
r?

[bug 1118765] Upgrade waffle to v0.10.1 for django 1.7

---

fjord/analytics/analyzer_views.py
fjord/analytics/forms.py
fjord/analytics/templates/analytics/analyzer/addproducts.html
fjord/feedback/admin.py

I missed these when I added the new column.
Quick r?

1111265 clean up

---

bin/peep-2.2.py
fjord/manage_utils.py
peep.sh

* update peep to 2.2
* fix a bug in manage_utils.py where it prints the wrong instructions
r?

Update peep to 2.2

---

fjord/heartbeat/sampledata.py
fjord/heartbeat/tests/__init__.py

[bug 1130474] Add sample data for heartbeat

---

requirements/requirements.txt

This adds revision of django-celery new django migrations.
r?

Update django-celery to master tip.

---

fjord/alerts/admin.py
fjord/alerts/migrations/0001_initial.py
fjord/alerts/models.py
fjord/alerts/tests/__init__.py
fjord/settings/base.py

This is the gist of the Alerts app.
r?

[bug 1130762] Alerts app, models and modelfactories

---

fjord/analytics/analyzer_views.py
fjord/analytics/forms.py
fjord/analytics/templates/analytics/analyzer/hb_surveys.html
fjord/analytics/urls.py

Add a create survey form so that users with relevant permissions can create surveys on their own.

[bug 1103045] Add create survey form

---

docs/alerts_api.rst
docs/index.rst
fjord/alerts/admin.py
fjord/alerts/api_views.py
fjord/alerts/migrations/0002_alertflavor_allowed_tokens.py
fjord/alerts/models.py
fjord/alerts/tests/test_api.py
fjord/alerts/urls.py
fjord/api_auth/admin.py
fjord/api_auth/migrations/0001_initial.py
fjord/api_auth/models.py
fjord/api_auth/tests/__init__.py
fjord/base/tests/__init__.py
fjord/settings/base.py
fjord/urls.py

* add api_auth Token system for Django user agnostic API permission
granting
* add alerts GET/POST API, docs and tests
r?

[bug 1130765] Implement Alerts API

---

docs/alerts_api.rst
fjord/alerts/api_views.py
fjord/alerts/tests/test_api.py

This is a recreation of pull #495 which I incorrectly based on a non-master branch.
r?

1130765 fix

---

fjord/search/tasks.py

This tweaks the code for live indexing so that we "ignore" amqp-related
issues. This will reduce the HTTP 500 errors users see when leaving
feedback during a rabbitmq outage.
r?

[bug 909011] Handle amqp-specific indexing errors

---

fjord/analytics/analyzer_views.py

[bug 1136810] Fix UnboundLocalError for "showdata"

---

docs/db.rst
fjord/alerts/migrations/0002_alertflavor_allowed_tokens.py
fjord/api_auth/migrations/0001_initial.py
fjord/heartbeat/migrations/0003_auto_20150225_1216.py
fjord/heartbeat/migrations/0004_auto_20150225_1232.py
fjord/heartbeat/migrations/0005_auto_20150225_1238.py
fjord/heartbeat/models.py

1136809 multiple obs

---

docs/getting_started.rst

`./manage.py migrate` is the new `./manage.py syncdb`
I missed this when upgrading. r?

Update setup docs for django 1.7.

---

requirements/requirements.txt

[bug 1136814] Update to Django 1.7.5

---

docs/alerts_api.rst
fjord/alerts/api_views.py
fjord/alerts/migrations/0003_auto_20150302_0712.py
fjord/alerts/models.py
fjord/alerts/tests/test_api.py

This adds start_time and end_time to the alerts api.
There isn't any code that uses it. Pretty sure the tests cover most/all situations.
r?

[bug 1137839] alerts timestamps

---

fjord/analytics/analyzer_views.py
fjord/analytics/templates/analytics/analyzer/hb_surveys.html
fjord/analytics/urls.py

Add a form for updating surveys using the CBVs and the same logic and template used in the create survey form

[bug 1103045] Add update survey form

---

requirements/requirements.txt

[bug 1048462] Upgrade gengo-python from 0.1.14 to 0.1.19

---

fjord/alerts/models.py
fjord/analytics/analyzer_views.py
fjord/analytics/templates/analytics/analyzer/hb_data.html
fjord/base/api_utils.py
fjord/heartbeat/migrations/0006_answer_received_ts.py
fjord/heartbeat/migrations/0007_auto_20150305_1119.py
fjord/heartbeat/models.py

* add a received_ts field to the hb Answer model with a silly
initial default value
* backfill the field with the data from updated_ts
r?

[bug 1139713] Add received_ts field to hb Answer model

---

fjord/heartbeat/migrations/0008_auto_20150305_1442.py

[bug 1139713] Fix received_ts migration

---

requirements/requirements.txt

r?
Also, sorry I'm doing these one at a time, but I'm pushing them out one at a time so as to reduce "omg! what happened" factor.

[bug 1048462] Upgrade django-multidb-router to 0.6

---

.gitmodules
fjord/base/static_utils.py
fjord/settings/base.py
requirements/requirements.txt

We weren't using django-compressor, except for a static finder which
turns out to be mostly a no-op. So we snuck out in the still of the
night and stole the secret plans for the one that kitsune has. NO ONE
WILL DENY US OUR STATIC FILES!
r?

[bug 1048462] Nix django-compressor

---

requirements/requirements.txt

[bug 1141153] Upgrade Django to 1.7.6

---

fjord/heartbeat/api_views.py

Pretty sure we can fix this just by wrapping it with a transaction, but
I still can't see what's going on. So for now, I'm going to log errors
so I can see what's going on.
r?

[bug 1139545] Wrap hb integrity error with logging

---

fjord/heartbeat/api_views.py

This tweaks the POST view so that it tries to create the object first.
That will fail with an IntegrityError because there's a uniqueness
constraint on (person_id, survey_id, flow_id). If it fails, then
there's already a record like this and it fetches that and updates it.
In this way, we use the db to eliminate the race condition between
the "get" and "create" steps which is kicking up the IntegrityErrors
we're seeing.
r?

[bug 1139545] Fix "get or create" section of HB post view

---

fjord/analytics/templates/analytics/dashboard.html
fjord/base/migrations/0003_remove_ditchchart_waffle_flag.py

Ditch ditchchart waffle flag from the checks. Remove the flag from
the database using the provided reversible migration.

[bug 1129102] ditch ditchchart flag

---

requirements/requirements.txt

[bug 1145118] Update Django to 1.7.7

---

docs/api.rst
fjord/feedback/api_views.py
fjord/feedback/tests/test_api.py

It's got tests and should be pretty straight-forward.
r?

[bug 1145307] Add id filter to feedback API GET

---

fjord/settings/base.py
fjord/settings/test.py

This should fix the travis issue we had.

[bug 1137022] Fix CACHES setting in tests

---

fjord/feedback/tests/test_views.py
fjord/feedback/views.py

@mythmon Can you eyeball these comments? Is the language correct?

[bug 1147227] Add notes about frames

---

fjord/feedback/models.py
fjord/feedback/views.py

[bug 1087379] Move methods to ProductManager

---

fjord/base/static/js/fjord_utils.js
fjord/feedback/static/js/generic_feedback.js
fjord/feedback/tests/test_views.py
fjord/feedback/views.py
smoketests/pages/generic_feedback_form.py
smoketests/tests/dashboard/test_redirects.py
smoketests/tests/generic/test_submit.py

1143881 prefill

---

fjord/settings/local.py-dist

This makes it easier to set up development locally.
@rlr Does this look ok? r?

Fix DATABASES and CACHES settings in local.py-dist

---

.travis.yml
bin/travis/install.sh
bin/travis/setup.sh

Work in progress. Tweaking Travis configuration.

[bug 1123746] Add ES 1.2.4 testing to travis test runs

---

fjord/base/static/css/fjord.less
fjord/base/templates/includes/footer.html
fjord/base/templates/includes/lang_switcher.html
fjord/feedback/static/css/generic_feedback.less
fjord/feedback/templates/feedback/thanks.html
fjord/feedback/views.py

This restyles the thank you page to match the generic feedback form
flow. It's now responsive and works on smaller screens. It doesn't
change any of the strings.
r?

[bug 1149517] Restyle thank you page

---

.editorconfig
docs/conventions.rst

Add the settings currently used by kitsune. Can add more specific settings later if required.

[bug 1087571] Codify editor settings using editorconfig

---

bin/lint_commit_msg.py

[bug 1156388] Fix EDITOR req in commit msg linter

---

bin/peep-2.4.py
peep.sh

I ran into issues with peep after updating pip to v6.1.1. This fixes that.
r?

Upgrade to peep 2.4

---

requirements/requirements.txt

And dependencies:
kombu to 3.0.26
billiard to 3.3.0.20
r?

[bug 1159867] Upgrade celery to 3.1.18

---

.travis.yml
bin/travis/dispatch.sh
bin/travis/djangocheck.sh
bin/travis/install.sh
bin/travis/setup.sh

Add "./manage.py check" to travis run

---

requirements/requirements.txt

[bug 1161084] Update Django to 1.7.8

---

.gitmodules
fjord/__init__.py
fjord/base/management/commands/celeryd.py
fjord/base/tasks.py
fjord/celery.py
fjord/manage_utils.py
fjord/search/tasks.py
fjord/settings/base.py
fjord/translations/tasks.py
requirements/requirements.txt
vendor/vendor.pth

* Use celery the way suggested in the docs.
* Create a celeryd command so our infra keeps working without changes.
* Move some monkeypatching stuff around.
There are some things that need to be cleaned up. Wanted to posted it like this so we can discuss. I'll add some comments inline.
f?

[bug 1144159] Remove usage of django-celery.

---

fjord/base/plugin_utils.py
fjord/settings/base.py
fjord/settings/test.py
fjord/suggest/__init__.py
fjord/suggest/apps.py
fjord/suggest/base.py
fjord/suggest/providers/dummy.py
fjord/suggest/providers/tests/__init__.py
fjord/suggest/providers/tests/test_dummy.py
fjord/suggest/utils.py

This implements a suggest framework that allows us to have a series of
Providers which offer suggested links to list on the Thank You page
after a user has given us feedback. Initially, we'll use this to generate
links for sad feedback based on SUMO data. We can additionally use this
for other purposes such as soliciting additional information based on
trigger words.
The world will be our oyster.
r?

[bug 1161144] Implement suggest framework

---

bin/travis/test.sh
requirements/dev.txt

[bug 1164069] Use nose-blockage on travis

---

requirements/requirements.txt

To test, run the tests after updating your vendor or virtual env.
r?

[bug 1164031] Update django-nose to v1.4

---

.pre-commit-config.yaml
docs/alerts_api.rst
fjord/alerts/api_views.py
fjord/alerts/tests/test_api.py

1161746 alerts

---

docs/alerts_api.rst
fjord/alerts/api_views.py
fjord/alerts/tests/test_api.py
fjord/base/api_utils.py

This changes the alerts get api to raise an http 400 if it gets bad
arguments.
r?

[bug 1164910] Raise http 400 for bad arguments in alerts api

---

fjord/feedback/migrations/0003_delete_empty_desc_feedback.py
fjord/feedback/migrations/0004_auto_20150518_1305.py
fjord/feedback/models.py

1165996 description

---

fjord/alerts/api_views.py
fjord/alerts/models.py
fjord/alerts/tests/test_api.py
fjord/api_auth/api_utils.py
fjord/base/api_utils.py
fjord/feedback/models.py
fjord/feedback/tests/test_api.py
fjord/heartbeat/api_views.py
fjord/heartbeat/models.py
requirements/requirements.txt

* upgrade to django-rest-framework 3.1.2
* update and clean up some api code without any backwards incompatible
changes
r?

[bug 1132455] Upgrade to django-rest-framework 3.1.2

---

.travis.yml

Remove ES 0.90.10 tests from travis

---

fjord/suggest/base.py
fjord/suggest/providers/dummy.py
fjord/suggest/providers/sumosuggest.py
fjord/suggest/tests/test_dummy.py
fjord/suggest/tests/test_sumosuggest.py

[bug 1167241] Add provider and provider_version to Link

---

fjord/alerts/api_views.py
fjord/base/utils.py
fjord/feedback/api_views.py
fjord/feedback/models.py
fjord/feedback/tests/test_api.py
fjord/heartbeat/api_views.py

* fix allow_blank=True on char fields that should allow blanks
* clean up some other code in what should be cosmetic ways
r?

[bug 1168475] Fix allow_blank on char fields

---

fjord/feedback/api_views.py

[bug 1077596] CORS-enable temporary histogram api

---

fjord/settings/travis.py-dist

Quick r?
Pretty sure this fixes the problem @rehandalal is having with pr #572.

Fix travis CACHES setting

---

fjord/feedback/tests/test_views.py
fjord/feedback/views.py
fjord/redirector/__init__.py
fjord/redirector/apps.py
fjord/redirector/base.py
fjord/redirector/providers/dummy.py
fjord/redirector/tests/__init__.py
fjord/redirector/tests/test_dummy.py
fjord/redirector/urls.py
fjord/redirector/views.py
fjord/settings/base.py
fjord/suggest/__init__.py
fjord/suggest/apps.py
fjord/suggest/base.py
fjord/suggest/providers/dummy.py
fjord/suggest/providers/sumosuggest.py
fjord/suggest/tests/__init__.py
fjord/suggest/tests/test_dummy.py
fjord/suggest/tests/test_sumosuggest.py
fjord/suggest/utils.py
fjord/urls.py

* implement redirector app
* add google_utils for pinging the server with events
* wrote SUMO Suggest redirector
* rework SUMO Suggester to use the redirector
* deal with the AAQ link
* minor renaming of things because I like to rename things over and over
again when it's raining
r?

[bug 1169261] Implement redirector

---

fjord/suggest/providers/sumosuggest.py

Event tracking needs the provider version number so we can distinguish
between flows for successive algorithms. Further, the "suggest" event
needs to be synchronous while the "view*" events can be asynchronous.
Sorry--forgot to do this. :(
r?

[bug 1169261] Fix event tracking

---

fjord/redirector/views.py

[bug 1169261] Never cache redirects

---

fjord/suggest/providers/sumosuggest.py

[bug 1173763] Add error logging to shed insight on issue

---

fjord/suggest/providers/sumosuggest.py

This logs everything to the journal so we can figure out what the
problem is.
Note: This is temporary. We'll remove this as soon as we figure it out.
Quick r?

[bug 1173763] Log everything

---

fjord/feedback/static/css/feedback.less
fjord/feedback/templates/feedback/generic_feedback.html

* made the text color match the face color
* reduced line-height of face description text
* tweaked font size for the aside
r?

[bug 1171498] First pass on style fixes

---

fjord/base/l10n.py
fjord/settings/base.py

I only brought the bits that collapse whitespace in blocks.
r?

[bug 1167192] Copy Jinja2 i18n extension from tower.

---

.gitmodules
fjord/base/l10n.py
fjord/base/management/commands/extract.py
fjord/base/management/commands/merge.py
fjord/settings/base.py
requirements/requirements.txt
vendor/vendor.pth

[bug 1167192] Copy tower commands over and remove tower dependency.

---

smoketests/pages/generic_feedback_form.py

A few weeks ago, I changed the class of the thing that the test looked
at, but didn't update the test. This updates the test.
r?

[bug 1183130] Fix test_picker.py smoketest

---

fjord/heartbeat/migrations/0009_answer_country.py
fjord/heartbeat/models.py

[bug 1183764] Add country field to hb answer model

---

.gitmodules
fjord/analytics/analyzer_views.py
fjord/analytics/templates/analytics/analyzer/search.html
fjord/analytics/templates/analytics/dashboard.html
fjord/analytics/tests/test_analyzer_views.py
fjord/analytics/tests/test_views.py
fjord/analytics/views.py
fjord/base/admin.py
fjord/base/views.py
fjord/feedback/api_views.py
fjord/feedback/models.py
fjord/feedback/tests/test_api.py
fjord/feedback/tests/test_models.py
fjord/search/__init__.py
fjord/search/admin.py
fjord/search/apps.py
fjord/search/index.py
fjord/search/models.py
fjord/search/tasks.py
fjord/search/tests/__init__.py
fjord/search/tests/test_index.py
fjord/search/tests/test_tasks.py
requirements/requirements.txt
vendor/vendor.pth

[bug 1170333] es

---

fjord/heartbeat/models.py

This adds indexes to the heartbeat Answer model to make querying faster
for Gregg.
Quick r?

[bug 1191822] Add indexes to heartbeat Answer model

---

fjord/heartbeat/migrations/0010_auto_20150806_0712.py

Migration for the recent index changes.
Quick r?

[bug 1191822] Add migration for index changes

---

fjord/base/browsers.py
fjord/base/tests/user_agent_data.json

[bug 1192812] Add support for Firefox for iOS user agents

---

fjord/alerts/tests/test_api.py

[bug 1193320] Remove eq_ and ok_ from fjord/alerts/

---

fjord/base/templates/mobile/base.html
fjord/feedback/templates/feedback/base.html
fjord/heartbeat/static/hb/experiment1/happy.html
fjord/heartbeat/static/hb/experiment1/neutral.html
fjord/heartbeat/static/hb/experiment1/sad.html

[bug 1194189] Fix scaling issue on iOS devices

---

fjord/base/migrations/0004_auto_20150817_1359.py
fjord/feedback/tests/test_views.py
fjord/feedback/views.py
fjord/suggest/tests/test_sumosuggest.py

We don't need thsi anymore, so we should remove it.
Quick r?

[bug 1195487] Remove "thankyou" flag

---

fjord/feedback/migrations/0006_remove_response_rating.py
fjord/feedback/models.py
fjord/feedback/tests/test_models.py

Gradients... we hardly knew you.
Quick r?

[bug 1194450] Remove rating

---

requirements/requirements.txt

[bug 1195899] Upgrade django to 1.7.10

---

fjord/analytics/forms.py
fjord/analytics/static/css/dashboard.less
fjord/analytics/templates/analytics/analyzer/addproducts.html
fjord/analytics/templates/analytics/analyzer/hb_surveys.html

This isn't anything fancy. Just tidies up the forms a bit. This is specific to analyzer forms, so as soon as Travis is green, I'm going to self-r+ this.

1196300 forms

---

fjord/heartbeat/tests/test_api.py

files under heartbeat directory. It replaces eq_ and ok_ with proper

[bug 1193326] Remove eq_ and ok_: heartbeat

---

fjord/base/data.py
fjord/base/management/commands/purge_data.py
fjord/base/tests/test_data.py
fjord/feedback/models.py
fjord/feedback/tests/test_models.py
fjord/journal/models.py
fjord/journal/tests/__init__.py
fjord/journal/tests/test_models.py

This rewrites the data purging system so that it's project-wide
infrastructure.
It also adds data purging for the journal.
r?

[bug 1112096] Add journal purging; rewrite data purging system

---

fjord/analytics/static/css/dashboard.less
fjord/analytics/templates/analytics/analyzer/dashboard.html
fjord/base/forms.py
fjord/feedback/tests/__init__.py
fjord/settings/base.py
fjord/suggest/providers/trigger/api_views.py
fjord/suggest/providers/trigger/migrations/0002_auto_20150831_0912.py
fjord/suggest/providers/trigger/models.py
fjord/suggest/providers/trigger/provider.py
fjord/suggest/providers/trigger/static/js/triggerrule.js
fjord/suggest/providers/trigger/templates/trigger/triggerrule_form.html
fjord/suggest/providers/trigger/tests/test_api.py
fjord/suggest/providers/trigger/tests/test_models.py
fjord/suggest/providers/trigger/urls.py

This lets trigger rule writers test the trigger rule against recent feedback.
r?

[Bug 1198766] tester

---

.gitmodules
bin/update_site.py

I don't know why it was still around--we don't use it anymore.

[bug 1202288] Remove jingo-minify

---

fjord/suggest/providers/trigger/forms.py
fjord/suggest/providers/trigger/provider.py
fjord/suggest/providers/trigger/tests/test_provider.py

This also adds tests for the redirector which I apparently didn't write the first time around. :(
r?

[bug 1198757] Add templated urls to trigger rule suggester

---

fjord/base/tests/test_utils.py
fjord/base/utils.py
fjord/feedback/api_views.py
fjord/feedback/tests/test_api.py
requirements/requirements.txt

1203119 ratelimit

---

fjord/analytics/analyzer_views.py
fjord/analytics/forms.py
fjord/analytics/templates/analytics/analyzer/dashboard.html
fjord/analytics/templates/analytics/analyzer/products.html
fjord/analytics/tests/test_analyzer_views.py
fjord/analytics/tests/test_views.py
fjord/analytics/urls.py
fjord/base/tests/test_views.py
fjord/feedback/tests/test_views.py
fjord/heartbeat/analyzer_views.py
fjord/heartbeat/api_views.py
fjord/heartbeat/forms.py
fjord/heartbeat/tests/test_analyzer_views.py
fjord/heartbeat/urls.py

1203173 analyzer tests

---

fjord/base/l10n.py
fjord/base/management/commands/extract.py
fjord/base/management/commands/merge.py
fjord/settings/base.py

* pep8 fixes
* removed some of the code needed for older versions of Babel
* renamed some things to reduce "tower" references

Cosmetic: Clean up extract, merge and l10n modules

---

docs/testing.rst

Periodically, we do substantive changes that affect the whole codebase.
We have a unit test suite and a set of smoketests, but there's a lot of
stuff that isn't covered by those.
Instead of writing up a test plan every time we do a substantive change,
this is an attempt at writing a comprehensive test plan covering all the
important things that we can reuse every time we do a substantive
change.
r?

[bug 1205013] Add comprehensive test plan

---

smoketests/pages/qunit.py
smoketests/tests/qunit/test_qunit.py

I lifted this code from Kitsune and modified it slightly so it works in the Fjord smoketest system.
Quick r?

[bug 1205370] Add smoketest for qunit tests

---

.gitmodules
fjord/analytics/views.py
fjord/base/utils.py
fjord/base/views.py
fjord/feedback/views.py
requirements/requirements.txt

We were only using mobile_template, so I grabbed that and then ditched
django-mobility.

[bug 1205296] Remove django-mobility

---

py.test
requirements/dev.txt

Dev requirements updated to the latest versions listed in https://requires.io/github/mozilla/fjord/requirements/?branch=master

Update dev requirements to the latest versions

---

fjord/feedback/models.py
fjord/feedback/tests/test_utils.py
fjord/feedback/tests/test_views.py
fjord/feedback/utils.py

This adds handling for emoji characters in feedback descriptions.

1221352 desc

---

fjord/base/management/commands/extract_db.py
fjord/feedback/db_strings.py

* switch from _lazy to pgettext
* redo the code that saves the files so that it's saving files in the
relevant app

[bug 1226601] Fix issues with extract_db command

---

fjord/mailinglist/admin.py
fjord/mailinglist/migrations/0001_initial.py
fjord/mailinglist/models.py
fjord/mailinglist/tests/__init__.py
fjord/mailinglist/tests/test_models.py
fjord/mailinglist/tests/test_utils.py
fjord/mailinglist/utils.py
fjord/settings/base.py

The mailing list system lets us associate names with lists of
recipients. A list of recipients is stored in a text field that allows
for arbitrary mailing list sizes, but also comments to make
managing the list easier.

Implement mailinglist system

---

fjord/heartbeat/tests/__init__.py

This makes it easier to have tests generate multiple surveys and
answers without hitting integrity issues.

Change some fields to use fuzzy values

---

fjord/analytics/jinja2/analytics/analyzer/dashboard.html
fjord/analytics/static/css/dashboard.less
fjord/heartbeat/analyzer_views.py
fjord/heartbeat/healthcheck.py
fjord/heartbeat/jinja2/analytics/analyzer/hb_data.html
fjord/heartbeat/jinja2/analytics/analyzer/hb_healthcheck.html
fjord/heartbeat/tests/test_analyzer_views.py
fjord/heartbeat/tests/test_healthchecks.py
fjord/heartbeat/urls.py

This adds an analyzer view that shows all the hb healthchecks and lets
you email the results to the mailing list. Further, it shows you the
recipients for the mailing list making it a little easier to make sure
things are set up correctly.

[bug 1232435] Add hb healthcheck view

---

fjord/feedback/jinja2/feedback/generic_feedback.html
fjord/feedback/static/js/generic_feedback.js

Here's to hoping the tests pass!
@mythmon r?

[bug 1155891] Modify language on feedback page for legal.

---

README.rst

Updates readthedocs and github urls.
r?

Update urls in README

---

README.rst
contribute.json
docs/conventions.rst
docs/es.rst
docs/l10n.rst
docs/maintain.rst
fjord/feedback/sampledata.py
fjord/settings/local.py-dist
vagrant/vagrant_provision.sh
vendor/README.txt

* switch to https urls
* switch to new readthedocs.io domain
r?

Update readthedocs urls
